### PR TITLE
Add meson buildsystem

### PR DESCRIPTION
**Pull request by albfan**
Ease to try samples and show an easy to use buildsystem

### CODE REVIEW

**Comment by gerito1** [comment]
I think it is a great improvement on the usage of the examples. I really appreciate it.
Put your name on the contribution list on the pull request and I will and I will merge.

**Comment by albfan** [comment]
Indeed, modify anything and just build is super quick.

> Put your name on the contribution list on the pull request and I will and I will merge.

Have no idea how to do that (I search around but can find how to do it) any link or example :cold_sweat:

**Comment by gerito1** [comment]
XD Instruction unclear. At the bottom in the Readme.md

**Comment by albfan** [comment]
done!

**Comment by gerito1** [comment]
🎉 Golden. Thank you very much you are awesome.

Ready for merge.

**Pull request merged**
